#!/bin/bash
#Premier outil de conversion (php en html)
docker image pull bigpapoo/sae4-php
docker container run \
    --rm \
    -ti \
    -p 9090:8080 \
    -v ${PWD}/../:/work \
bigpapoo/sae4-php php scripts/builder.php -f samples/mono.json > ../modele/modele.html

#Si la commande précédente a réussi, on continue
if [ $? -eq 0 ]; then
    echo "Conversion terminée, fichier modele.html disponible dans le dossier modele";

    #Deuxième outil de conversion (html en pdf)
    docker image pull bigpapoo/sae4-html2pdf
    docker container run \
        --rm \
        -ti \
        -v ${PWD}/../:/work \
    bigpapoo/sae4-html2pdf "html2pdf modele/modele.html catalogue.pdf"
else
    echo "Erreur: Le fichier json n'existe pas";
fi

#Tests
#Pour que les dockers restent actifs et regarder ce qu'il y a dedans (par exemple : docker exec [id] ls) tu peux faire ça :
#Docker 1 (sae4-php) : rajoute "php -S localhost:6666" à la place de php scripts/builder.php > ../modele/modele.html
#Docker 2 (sae4-html2pdf) : rajoute "sleep 999999999" à la place de "html2pdf modele/modele.html modele/fichier.pdf"